
development: &development
  adapter: postgresql
  database: sample_app_development

production:
  <<: *development

test: &test
  adapter: postgresql
  database: sampe_app_test
  min_messages: warning
